language: java

sudo: false

env:
  global:
    - jdk6file=zulu6.22.0.3-jdk6.0.119-linux_x64
    - jdk8file=OpenJDK8U-jdk_x64_linux_hotspot_8u232b09
    - sercoll_jdk6_java=${TRAVIS_BUILD_DIR}/${jdk6file}/bin/java
    - sercoll_jdk6_javac=${TRAVIS_BUILD_DIR}/${jdk6file}/bin/javac
    - sercoll_jdk6_javadoc=${TRAVIS_BUILD_DIR}/${jdk6file}/bin/javadoc

before_install:
  - 'curl -JORL https://cdn.azul.com/zulu/bin/${jdk6file}.tar.gz'
  - 'curl -JORL https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u232-b09/${jdk8file}.tar.gz'
  - 'tar -xf ${jdk6file}.tar.gz'
  - 'tar -xf ${jdk8file}.tar.gz'
  - 'ls -lF'
  - 'export JAVA_HOME=${PWD}/jdk8u232-b09'
  - 'echo JAVA_HOME=${JAVA_HOME}'
  - 'export PATH=${JAVA_HOME}/bin:${PATH}'
  - 'java -version'
  - 'ls -l ${sercoll_jdk6_java}'
  - 'ls -a'
  - 'pwd'
  - './gradlew clean'

cache:
  directories:
  - ~/.gradle

branches:
  only:
  - master
