language: java

sudo: false

jdk: oraclejdk8

# Update JDK8 to latest version available for Travis
addons:
  apt:
    packages:
      - openjdk-6-jdk
      - oracle-java8-installer

env:
  global:
  - sercoll_jdk6_java=/usr/lib/jvm/java-6-openjdk-amd64/bin/java
  - sercoll_jdk6_javac=/usr/lib/jvm/java-6-openjdk-amd64/bin/javac
  - sercoll_jdk6_javadoc=/usr/lib/jvm/java-6-openjdk-amd64/bin/javadoc

before_install:
  - ls -a
  - pwd
  - ./gradlew clean

cache:
  directories:
  - ~/.gradle

branches:
  only:
  - master
