name: build

on: [push, pull_request, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: gradle:7.0.2-jdk8
            env:
                DEBIAN_FRONTEND: noninteractive
                ZULU_HOME: /usr/lib/jvm/zulu-6-amd64
                sercoll_jdk6_java: /usr/lib/jvm/zulu-6-amd64/bin/java
                sercoll_jdk6_javac: /usr/lib/jvm/zulu-6-amd64/bin/javac
                sercoll_jdk6_javadoc: /usr/lib/jvm/zulu-6-amd64/bin/javadoc
        steps:
            - name: upgrade-git
              run: |
                  apt-get update
                  apt-get install -y software-properties-common
                  add-apt-repository -y ppa:git-core/ppa
                  apt-get update
                  apt-get install -y git

            - name: add-jdk6
              run: |
                  apt-get -y install gnupg
                  apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xB1998361219BD9C9
                  curl -LO https://cdn.azul.com/zulu/bin/zulu6.22.0.3-jdk6.0.119-linux_amd64.deb
                  apt-get install -y ./zulu6.22.0.3-jdk6.0.119-linux_amd64.deb

            - name: versions
              run: |
                  echo PATH=${PATH}
                  git --version
                  echo JAVA_HOME=${JAVA_HOME}
                  ls -l ${JAVA_HOME}/bin/java
                  java -version
                  echo ZULU_HOME=${ZULU_HOME}
                  ls -l ${sercoll_jdk6_java}
                  ${ZULU_HOME}/bin/java -version

            - uses: actions/checkout@v2

            - name: build
              run: gradle clean build
